---
- hosts: all
  become: true
  environment:
    https_proxy: http://192.168.56.101:3128  
  roles:
    - role: ansible-role-cockroachdb
  post_tasks:
    - name: enable /etc/rc.local
      file:
        path: /etc/rc.local
        owner: root
        group: root        
        mode: 755
    - name: check 1 /etc/rc.local
      lineinfile:
        dest: /etc/rc.local
        line: "#!/bin/sh -e"
        insertbefore: BOF      
    - name: check 2 /etc/rc.local
      lineinfile:
        dest: /etc/rc.local
        line: exit 0
        state: present
        insertafter: EOF
    - name: "add cockroachdb on startup"
      lineinfile:
        dest: /etc/rc.local
        line: /opt/apps/cockroachdb/start.sh
        insertbefore: exit 0
    - name: "start cockroachdb"
      shell: "/opt/apps/cockroachdb/start.sh"
     
